### ISSUE TITLE
File not found error with PDFLaTeX

### ISSUE THREAD

**Issue by andrewschalk** [andrewschalk/Nice-Tabs#10]
This seems to be an error caused by PDFLaTeX, when it creates the subprocess used to compile the pdf document, this error is thrown.  The code works fine on one computer but throws this error on another. May have to do with tempfile shorting directory that has white space. It's likely that I'll need to fork and edit PDFLaTeX for this as well as updating its required dependencies.

```
Traceback (most recent call last):
  File "c:\Users\Andrew Schalk\Documents\Programming\Nice-Tabs\src\nice_tabs\processes.py", line 133, in _save_file
    pdf_latex.create_pdf(keep_pdf_file=True)
  File "C:\Users\Andrew Schalk\Documents\Programming\Nice-Tabs\venv\Lib\site-packages\pdflatex\pdflatex.py", line 77, in create_pdf
    fp = subprocess.run(args, input=self.latex, env=env, timeout=15, stdout=PIPE, stderr=PIPE)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by andrewschalk** [comment]
Issue caused by not having an installation of pdflatex
