### ISSUE TITLE
PyLaTeX permissions issue

### ISSUE THREAD

**Issue by andrewschalk** [andrewschalk/Nice-Tabs#6]
On some systems pylatex throws a permissions error when trying to save.

**Comment by andrewschalk** [comment]
Traceback (most recent call last):
  File "d:\ProgrammingProjects\Nice-Tabs\NiceTabs.pyw", line 199, in tabConverter
    doc.generate_pdf(file.replace('.pdf',''),clean_tex=generateTex.get(),compiler='venv/Lib/site-packages/pdflatex-0.1.3.dist-info')
  File "D:\ProgrammingProjects\Nice-Tabs\venv\lib\site-packages\pylatex\document.py", line 250, in generate_pdf
    output = subprocess.check_output(command,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied

**Comment by andrewschalk** [comment]
Not able to fix this permissions issue. Instead use the PDF generation from PDF latex directly. PDF generation works now
